context.annotation.value.empty=The property "value" on the annotation @org.kaleidofoundry.core.context.Context is missing

context.annotation.illegaluse.noRuntimeContextField=The field "{0}" is annotated with "{1}", but its class does not contains org.kaleidofoundry.core.context.RuntimeContext<?> field.
context.annotation.illegalinject=Context "{0}" have already been injected.
context.annotation.illegalfield=org.kaleidofoundry.core.context.RuntimeContext field "{0}#{1}" is final and null, it can''t be injected.
context.annotation.illegalconfig.simple=Illegal configuration definition in annotation @org.kaleidofoundry.core.context.Context(value="{0}", configurations=''{''..,"{1}",..''}''). The configuration "{1}" may not have been registered ?
context.annotation.missing=The annotation @org.kaleidofoundry.core.context.Context is missing on the field / argument "{0}"

context.parameter.empty=The parameter "{0}" have to be setted for context "{1}"
context.parameter.causes.error=The parameter "{0}={1}" in context "{2}" causes error: "{3}"
context.parameter.illegal.use=Illegal use of the parameter "{0}={1}" in context "{2}", reason: "{3}"

# introspection error
context.provider.error.NoSuchConstructorException=Class "{0}" does not define a constructor like: {0}({1})
context.provider.error.InstantiationException=Class "{0}" can''t be instantiate due to underlying error: "{1}"
context.provider.error.IllegalAccessException=Class "{0}" does not define a accessible constructor like: {0}({1})
context.provider.error.InvocationTargetException=Error during constructor call "{0}({1})" - please check the stack trace following.

context.provider.error.default=Error has occurred due to nested exception.